---
params:
  fname: "default"
  dir_data: "default"
  exp_type: "slamdunk" # slamdunk or smallslam
  
title: "SLAMtrack - mutation rates"
subtitle: "`r params$fname`"
author: "RWH"
date: "`r format(Sys.time(), '%d %B %Y')`"

output: 
  html_document:
    theme: readable 
    highlight: pygments 
    anchor_sections: FALSE

---

```{r setup, include=FALSE}

if (params$exp_type == "slamdunk") {is_slamdunk <- TRUE} else {is_slamdunk <- FALSE}
dir_data <<- params$dir_data  ## <<- to make global variable
exp_type <<- params$exp_type

source(".Rprofile")
source("scripts/SLAMtrack_00_setup.R")
source("scripts/SLAMtrack_11_import_quick.R")

knitr::opts_chunk$set(
  echo = FALSE, 
  error = TRUE, 
  message = FALSE
  # fig.path = paste0(dir_data, "output/") - don't know why this not working
  )

```


# Analysis

All reads over a threshold read count of `r mutations_threshold_readcount` analysed to give strand-specific mutation rates.  Expect T>C conversions on the +ve strand and A>G conversions on the -ve strand.  


## Mutation rates in the tissue of origin

```{r mutations_tissue_origin, eval=is_slamdunk}

df_meta_short %>% 
  left_join(df_mutations_L) %>% 
  filter(tissue == exp_tissue_origin) %>% 
  reshape_mutations_for_TABACO(plot_strand = "+") %>% 
  plot_TABACO_grid_rates() +
  ggtitle(paste("Mutation rates in", exp_tissue_origin, "\non the +ve strand"))

df_meta_short %>% 
  left_join(df_mutations_L) %>% 
  filter(tissue == exp_tissue_origin) %>% 
  reshape_mutations_for_TABACO(plot_strand = "-") %>% 
  plot_TABACO_grid_rates() +
  ggtitle(paste("Mutation rates in", exp_tissue_origin, "\non the -ve strand"))

```

## Mutation rates in the target tissue

```{r mutations_tissue_target, eval=is_slamdunk}

df_meta_short %>% 
  left_join(df_mutations_L) %>% 
  filter(tissue == exp_tissue_target) %>% 
  reshape_mutations_for_TABACO(plot_strand = "+") %>% 
  plot_TABACO_grid_rates_zoom(0.003) +
  ggtitle(paste("Mutation rates in", exp_tissue_target, "\non the +ve strand"))

df_meta_short %>% 
  left_join(df_mutations_L) %>% 
  filter(tissue == exp_tissue_target) %>% 
  reshape_mutations_for_TABACO(plot_strand = "-") %>% 
  plot_TABACO_grid_rates_zoom(0.003) +
  ggtitle(paste("Mutation rates in", exp_tissue_target, "\non the -ve strand"))

```
